import type { ClassRoom, Student, AttendanceRecord, LessonExtract, YearlyPlanItem, TeacherSettings } from '../types';

export const initialSettings: TeacherSettings = {
  teacherName: 'ស៊ឹម វីរៈ',
  schoolName: 'វិទ្យាល័យ ហ៊ុន សែន មិត្តភាព',
  schoolCode: 'HS-MTP-088',
  principalName: 'ហេង ពិសាល',
  specialtySubject: 'ភាសាខ្មែរ និងអក្សរសិល្ប៍',
  academicYear: '២០២៤-២០២៥',
  provinceCity: 'រាជធានីភ្នំពេញ',
  absenceWarningThreshold: 3,
  phone: '012 889 900',
  email: 'sim.virak@moeys.edu.kh',
};

export const initialClasses: ClassRoom[] = [
  {
    id: 'class-7a',
    name: 'ថ្នាក់ទី ៧ ក',
    grade: '៧',
    academicYear: '២០២៤-២០២៥',
    room: 'បន្ទប់ ១០១ (អគារ A)',
    description: 'ថ្នាក់បំប៉នភាសាខ្មែរ និងគណិតវិទ្យា',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'class-8b',
    name: 'ថ្នាក់ទី ៨ ខ',
    grade: '៨',
    academicYear: '២០២៤-២០២៥',
    room: 'បន្ទប់ ២០៣ (អគារ B)',
    description: 'ថ្នាក់ចំណេះទូទៅ',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'class-10a',
    name: 'ថ្នាក់ទី ១០ វិទ្យាសាស្ត្រ',
    grade: '១០',
    academicYear: '២០២៤-២០២៥',
    room: 'បន្ទប់ ៣០២ (អគារ C)',
    description: 'ថ្នាក់វិទ្យាសាស្ត្រពិត',
    createdAt: '2024-10-01T08:00:00Z',
  },
];

export const initialStudents: Student[] = [
  {
    id: 'stu-7a-01',
    classId: 'class-7a',
    rollNo: 1,
    studentCode: 'STU-7A-001',
    nameKh: 'កែវ មុន្នីរ័ត្ន',
    nameEn: 'Keo Monyrath',
    gender: 'ស្រី',
    dob: '2011-03-15',
    pob: 'ស្រុកកៀនស្វាយ ខេត្តកណ្តាល',
    currentAddress: 'ភូមិដើមចាន់ សង្កាត់ច្បារអំពៅ ភ្នំពេញ',
    guardianName: 'កែវ វិបុល',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '012 345 678',
    guardianOccupation: 'មន្ត្រីរាជការ',
    notes: 'សិស្សរៀនពូកែ និងមានវិន័យល្អ',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-02',
    classId: 'class-7a',
    rollNo: 2,
    studentCode: 'STU-7A-002',
    nameKh: 'ចាន់ សុខា',
    nameEn: 'Chan Sokha',
    gender: 'ប្រុស',
    dob: '2011-06-22',
    pob: 'ស្រុកស្អាង ខេត្តកណ្តាល',
    currentAddress: 'ផ្ទះលេខ ៤៥ ផ្លូវ ៣៦០ បឹងកេងកង ភ្នំពេញ',
    guardianName: 'ចាន់ សុវណ្ណ',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '098 765 432',
    guardianOccupation: 'អាជីវករ',
    notes: 'ឧស្សាហ៍អវត្តមានដោយសារជួយការងារផ្ទះ',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-03',
    classId: 'class-7a',
    rollNo: 3,
    studentCode: 'STU-7A-003',
    nameKh: 'ឈន ពិសិដ្ឋ',
    nameEn: 'Chhorn Piseth',
    gender: 'ប្រុស',
    dob: '2011-01-10',
    pob: 'រាជធានីភ្នំពេញ',
    currentAddress: 'សង្កាត់បឹងសាឡាង ខណ្ឌទួលគោក ភ្នំពេញ',
    guardianName: 'ម៉ៅ ស្រីមុំ',
    guardianRelationship: 'ម្តាយ',
    guardianPhone: '077 112 233',
    guardianOccupation: 'បុគ្គលិកក្រុមហ៊ុន',
    notes: '',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-04',
    classId: 'class-7a',
    rollNo: 4,
    studentCode: 'STU-7A-004',
    nameKh: 'ដួង ចរិយា',
    nameEn: 'Doung Chariya',
    gender: 'ស្រី',
    dob: '2011-09-08',
    pob: 'ស្រុកបាទី ខេត្តតាកែវ',
    currentAddress: 'សង្កាត់ស្ទឹងមានជ័យ ខណ្ឌមានជ័យ ភ្នំពេញ',
    guardianName: 'ដួង សម្បត្តិ',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '085 445 566',
    guardianOccupation: 'កសិករ',
    notes: 'ប្រធានថ្នាក់',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-05',
    classId: 'class-7a',
    rollNo: 5,
    studentCode: 'STU-7A-005',
    nameKh: 'ណុប វឌ្ឍនៈ',
    nameEn: 'Nop Vathanak',
    gender: 'ប្រុស',
    dob: '2011-11-19',
    pob: 'ក្រុងកំពង់ចាម ខេត្តកំពង់ចាម',
    currentAddress: 'សង្កាត់ទួលសង្កែ ខណ្ឌឫស្សីកែវ ភ្នំពេញ',
    guardianName: 'ណុប សុផល',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '015 667 788',
    guardianOccupation: 'វិស្វករ',
    notes: 'អវត្តមានច្រើនដងដោយគ្មានការអនុញ្ញាត',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-06',
    classId: 'class-7a',
    rollNo: 6,
    studentCode: 'STU-7A-006',
    nameKh: 'ទូច សោភា',
    nameEn: 'Touch Sophea',
    gender: 'ស្រី',
    dob: '2011-04-05',
    pob: 'ខេត្តព្រៃវែង',
    currentAddress: 'សង្កាត់ផ្សារដេប៉ូ ខណ្ឌទួលគោក ភ្នំពេញ',
    guardianName: 'ទូច វណ្ណា',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '097 889 900',
    guardianOccupation: 'គ្រូបង្រៀន',
    notes: '',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-07',
    classId: 'class-7a',
    rollNo: 7,
    studentCode: 'STU-7A-007',
    nameKh: 'ភួង គីមឡុង',
    nameEn: 'Phuong Kimlong',
    gender: 'ប្រុស',
    dob: '2011-07-14',
    pob: 'រាជធានីភ្នំពេញ',
    currentAddress: 'សង្កាត់ទឹកល្អក់៣ ខណ្ឌទួលគោក ភ្នំពេញ',
    guardianName: 'អ៊ុំ សុគន្ធា',
    guardianRelationship: 'ម្តាយ',
    guardianPhone: '010 223 344',
    guardianOccupation: 'មេផ្ទះ',
    notes: 'សុខភាពខ្សោយ ឧស្សាហ៍សុំច្បាប់',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-08',
    classId: 'class-7a',
    rollNo: 8,
    studentCode: 'STU-7A-008',
    nameKh: 'ម៉េង ស្រីលីន',
    nameEn: 'Meng Sreylin',
    gender: 'ស្រី',
    dob: '2011-12-03',
    pob: 'ស្រុកកណ្តាលស្ទឹង ខេត្តកណ្តាល',
    currentAddress: 'សង្កាត់ចោមចៅ ខណ្ឌពោធិ៍សែនជ័យ ភ្នំពេញ',
    guardianName: 'ម៉េង ហេង',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '096 554 433',
    guardianOccupation: 'កម្មកររោងចក្រ',
    notes: '',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-09',
    classId: 'class-7a',
    rollNo: 9,
    studentCode: 'STU-7A-009',
    nameKh: 'យិន បញ្ញា',
    nameEn: 'Yin Panha',
    gender: 'ប្រុស',
    dob: '2011-02-28',
    pob: 'ក្រុងសៀមរាប ខេត្តសៀមរាប',
    currentAddress: 'សង្កាត់គីឡូម៉ែត្រលេខ៦ ខណ្ឌឫស្សីកែវ ភ្នំពេញ',
    guardianName: 'យិន សម្បត្តិ',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '089 998 877',
    guardianOccupation: 'មគ្គុទ្ទេសក៍ទេសចរណ៍',
    notes: 'សកម្មក្នុងកិច្ចការថ្នាក់',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-7a-10',
    classId: 'class-7a',
    rollNo: 10,
    studentCode: 'STU-7A-010',
    nameKh: 'លីណា ដាលីន',
    nameEn: 'Lina Dalin',
    gender: 'ស្រី',
    dob: '2011-08-17',
    pob: 'រាជធានីភ្នំពេញ',
    currentAddress: 'សង្កាត់ព្រែកប្រា ខណ្ឌច្បារអំពៅ ភ្នំពេញ',
    guardianName: 'លីណា សារុន',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '011 334 455',
    guardianOccupation: 'អ្នកបើកបរ',
    notes: '',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  // Students for Class 8B
  {
    id: 'stu-8b-01',
    classId: 'class-8b',
    rollNo: 1,
    studentCode: 'STU-8B-001',
    nameKh: 'សុខ ជា',
    nameEn: 'Sok Chea',
    gender: 'ប្រុស',
    dob: '2010-05-12',
    pob: 'ខេត្តកំពង់ស្ពឺ',
    currentAddress: 'សង្កាត់ស្រះចក ខណ្ឌដូនពេញ',
    guardianName: 'សុខ គង់',
    guardianRelationship: 'ឪពុក',
    guardianPhone: '012 990 011',
    notes: '',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  },
  {
    id: 'stu-8b-02',
    classId: 'class-8b',
    rollNo: 2,
    studentCode: 'STU-8B-002',
    nameKh: 'ទៀង កល្យាណ',
    nameEn: 'Tieng Kallyan',
    gender: 'ស្រី',
    dob: '2010-09-24',
    pob: 'ខេត្តបាត់ដំបង',
    currentAddress: 'សង្កាត់ទួលទំពូង ខណ្ឌចំការមន',
    guardianName: 'ទៀង ផល្លា',
    guardianRelationship: 'ម្តាយ',
    guardianPhone: '070 882 211',
    notes: '',
    status: 'active',
    createdAt: '2024-10-01T08:00:00Z',
  }
];

export const initialAttendance: AttendanceRecord[] = [
  // Student 2 (Chan Sokha) - 4 Absences (Needs warning letter!)
  {
    id: 'att-1',
    classId: 'class-7a',
    studentId: 'stu-7a-02',
    date: '2024-10-07',
    session: 'morning',
    status: 'absent',
    reason: 'គ្មានដំណឹងពីអាណាព្យាបាល',
    createdAt: '2024-10-07T08:00:00Z'
  },
  {
    id: 'att-2',
    classId: 'class-7a',
    studentId: 'stu-7a-02',
    date: '2024-10-08',
    session: 'morning',
    status: 'absent',
    reason: 'អវត្តមានឥតច្បាប់',
    createdAt: '2024-10-08T08:00:00Z'
  },
  {
    id: 'att-3',
    classId: 'class-7a',
    studentId: 'stu-7a-02',
    date: '2024-10-14',
    session: 'morning',
    status: 'absent',
    reason: 'អវត្តមានឥតច្បាប់លើកទី ៣',
    createdAt: '2024-10-14T08:00:00Z'
  },
  {
    id: 'att-4',
    classId: 'class-7a',
    studentId: 'stu-7a-02',
    date: '2024-10-15',
    session: 'morning',
    status: 'absent',
    reason: 'អវត្តមានឥតច្បាប់លើកទី ៤ (ប្រឈមការព្រមាន)',
    createdAt: '2024-10-15T08:00:00Z'
  },

  // Student 5 (Nop Vathanak) - 3 Absences
  {
    id: 'att-5',
    classId: 'class-7a',
    studentId: 'stu-7a-05',
    date: '2024-10-04',
    session: 'morning',
    status: 'absent',
    reason: 'មិនបានចូលរៀន',
    createdAt: '2024-10-04T08:00:00Z'
  },
  {
    id: 'att-6',
    classId: 'class-7a',
    studentId: 'stu-7a-05',
    date: '2024-10-11',
    session: 'morning',
    status: 'absent',
    reason: 'មិនបានចូលរៀន',
    createdAt: '2024-10-11T08:00:00Z'
  },
  {
    id: 'att-7',
    classId: 'class-7a',
    studentId: 'stu-7a-05',
    date: '2024-10-18',
    session: 'morning',
    status: 'absent',
    reason: 'អវត្តមានលើកទី៣ ជាប់គ្នា',
    createdAt: '2024-10-18T08:00:00Z'
  },

  // Student 7 (Phuong Kimlong) - 2 Permissions (ច្បាប់)
  {
    id: 'att-8',
    classId: 'class-7a',
    studentId: 'stu-7a-07',
    date: '2024-10-09',
    session: 'morning',
    status: 'permission',
    reason: 'មានជំងឺផ្តាសាយធ្ងន់ធ្ងរ',
    createdAt: '2024-10-09T08:00:00Z'
  },
  {
    id: 'att-9',
    classId: 'class-7a',
    studentId: 'stu-7a-07',
    date: '2024-10-10',
    session: 'morning',
    status: 'permission',
    reason: 'ទៅពេទ្យពិនិត្យសុខភាព',
    createdAt: '2024-10-10T08:00:00Z'
  },

  // Regular attendance for today (Present)
  {
    id: 'att-10',
    classId: 'class-7a',
    studentId: 'stu-7a-01',
    date: '2024-10-18',
    session: 'morning',
    status: 'present',
    createdAt: '2024-10-18T08:00:00Z'
  },
  {
    id: 'att-11',
    classId: 'class-7a',
    studentId: 'stu-7a-03',
    date: '2024-10-18',
    session: 'morning',
    status: 'present',
    createdAt: '2024-10-18T08:00:00Z'
  },
  {
    id: 'att-12',
    classId: 'class-7a',
    studentId: 'stu-7a-04',
    date: '2024-10-18',
    session: 'morning',
    status: 'late',
    reason: 'ស្ទះចរាចរណ៍លើដងផ្លូវ',
    createdAt: '2024-10-18T08:00:00Z'
  },
  {
    id: 'att-13',
    classId: 'class-7a',
    studentId: 'stu-7a-06',
    date: '2024-10-18',
    session: 'morning',
    status: 'present',
    createdAt: '2024-10-18T08:00:00Z'
  },
];

export const initialExtracts: LessonExtract[] = [
  {
    id: 'ext-1',
    title: 'សម្រង់ឱវាទអប់រំ សម្តេចព្រះសង្ឃរាជ ជួន ណាត',
    subject: 'ភាសាខ្មែរ / សីលធម៌ពលរដ្ឋ',
    grade: 'ទូទៅ',
    category: 'quote',
    content: `«ជាតិមួយរុងរឿងទៅបាន អាស្រ័យដោយប្រជាពលរដ្ឋមានចំណេះដឹង និងសីលធម៌ខ្ពង់ខ្ពស់។ យុវជនគឺជាសសរទ្រូងនៃប្រទេសជាតិ ប្រសិនបើយុវជនខិតខំរៀនសូត្រ ប្រកាន់ខ្ជាប់នូវវិន័យ និងកតញ្ញុតាធម៌ចំពោះមាតាបិតា និងគ្រូបាអាចារ្យ នោះអនាគតជាតិមុខជានឹងថ្កុំថ្កើងរុងរឿងជាពុំខាន។ ចូរកុំបណ្តែតបណ្តោយពេលវេលាឱ្យកន្លងផុតទៅដោយឥតប្រយោជន៍ ព្រោះពេលវេលាមាសប្រាក់កាលណាកន្លងផុតទៅហើយ មិនអាចត្រឡប់មកវិញឡើយ។»`,
    source: 'កម្រងពាក្យប្រៀនប្រដៅ សម្តេចព្រះសង្ឃរាជ ជួន ណាត ជោតញ្ញាណោ',
    tags: ['សីលធម៌', 'ការអប់រំ', 'យុវជន', 'ជាតិ'],
    createdAt: '2024-10-02T10:00:00Z'
  },
  {
    id: 'ext-2',
    title: 'សម្រង់អក្សរសិល្ប៍៖ រឿង «ទុំទាវ» ឈុតទុំច្រៀងសារភាព',
    subject: 'អក្សរសិល្ប៍ខ្មែរ',
    grade: '៧-៩',
    category: 'reading',
    content: `«ស្រណោះផ្កាគន្ធ មានក្លិនក្រអូបឈ្ងុយឈ្ងប់
រាត្រីយប់ស្ងាត់ ចន្ទ្រារះថ្លា
ទុំច្រៀងរៀបរាប់ តាមបទចិន្តា
ជូននាងកល្យាណ កែវទាវពិសី...

ទំនុកច្រៀងពិរោះ រណ្តំដួងចិត្ត
ធ្វើឱ្យនាងទាវ ញាប់ញ័រហឫទ័យ
ដឹងច្បាស់ថាទុំ ស្ម័គ្រស្មោះភក្តី
ទោះបីមានឧបសគ្គ ក៏មិនរាថយ។»`,
    source: 'រឿងទុំទាវ - ព្រះភិក្ខុសោម',
    tags: ['អក្សរសិល្ប៍', 'ទុំទាវ', 'កំណាព្យ', 'សិល្បៈ'],
    createdAt: '2024-10-05T14:30:00Z'
  },
  {
    id: 'ext-3',
    title: 'រូបមន្តគណិតវិទ្យាគ្រឹះ៖ ផ្ទៃក្រឡា និងបរិមាត្រធរណីមាត្រ',
    subject: 'គណិតវិទ្យា',
    grade: '៧-៨',
    category: 'formula',
    content: `១. ចតុកោណកែង៖
   - បរិមាត្រ P = 2 × (បណ្តោយ + ទទឹង) = 2(a + b)
   - ផ្ទៃក្រឡា S = បណ្តោយ × ទទឹង = a × b

២. ការ៉េ៖
   - បរិមាត្រ P = 4 × ជ្រុង = 4a
   - ផ្ទៃក្រឡា S = ជ្រុង × ជ្រុង = a²

៣. ត្រីកោណ៖
   - ផ្ទៃក្រឡា S = (បាត × កម្ពស់) ÷ 2 = (b × h) / 2

៤. រង្វង់៖
   - បរិមាត្រ (ប្រវែងរង្វង់) C = 2 × π × r (π ≈ 3.14)
   - ផ្ទៃក្រឡា S = π × r²`,
    source: 'សៀវភៅសិក្សាគោលគណិតវិទ្យា ថ្នាក់ទី៧ ក្រសួងអប់រំ យុវជន និងកីឡា',
    tags: ['គណិតវិទ្យា', 'រូបមន្ត', 'ធរណីមាត្រ', 'ផ្ទៃក្រឡា'],
    createdAt: '2024-10-08T09:15:00Z'
  },
  {
    id: 'ext-4',
    title: 'អត្ថបទសរសេរតាមអាន៖ «គុណូបការៈនៃគ្រូបង្រៀន»',
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    category: 'dictation',
    content: `«លោកគ្រូ អ្នកគ្រូ គឺជាវិស្វករនៃព្រលឹងវិញ្ញាណ និងជាអ្នកកសាងធនធានមនុស្សដ៏ឆ្នើមសម្រាប់សង្គមជាតិ។ លោកតែងតែលះបង់កម្លាំងកាយចិត្ត ប្រាជ្ញាស្មារតី ក្នុងការផ្ទេរចំណេះដឹង បណ្តុះបណ្តាលគំនិត និងចរិយាសម្បត្តិដល់សិស្សានុសិស្សគ្រប់រូប។ គុណូបការៈរបស់លោកគ្រូអ្នកគ្រូធំធេងឥតឧបមា ប្រៀបដូចជាពន្លឺប្រទីបដែលបំភ្លឺផ្លូវឱ្យយើងដើរចៀសផុតពីអវិជ្ជា និងភាពងងឹតសូន្យសុង។ ក្នុងនាមជាសិស្ស យើងត្រូវតែគោរព ដឹងគុណ និងយកចិត្តទុកដាក់ស្តាប់ដំបូន្មានរបស់លោកជានិច្ច។»`,
    source: 'អត្ថបទដកស្រង់សម្រាប់ការសរសេរតាមអាន ឆមាសទី១',
    tags: ['សរសេរតាមអាន', 'គុណគ្រូ', 'ភាសាខ្មែរ', 'តែងសេចក្តី'],
    createdAt: '2024-10-12T11:00:00Z'
  },
  {
    id: 'ext-5',
    title: 'ខ្លឹមសារមេរៀនសង្ខេប៖ វិធានវេយ្យាករណ៍ «កន្សោមនាម និងកន្សោមកិរិយា»',
    subject: 'ភាសាខ្មែរ',
    grade: '៧-៨',
    category: 'lesson_summary',
    content: `១. កន្សោមនាម (Noun Phrase):
- គឺជាកន្សោមពាក្យដែលមាន "នាម" ជាស្នូលចម្បង ហើយអាចអមដោយគុណនាម ចំនួនរាប់ ឬពាក្យចង្អុលបង្ហាញ។
- ឧទាហរណ៍៖ «សិស្សឧស្សាហ៍ទាំងបីនាក់នោះ» (នាមស្នូល: សិស្ស)

២. កន្សោមកិរិយា (Verb Phrase):
- គឺជាកន្សោមពាក្យដែលមាន "កិរិយាសព្ទ" ជាស្នូលចម្បង។
- ឧទាហរណ៍៖ «កំពុងតែខិតខំរៀនសូត្រយ៉ាងសកម្ម» (កិរិយាស្នូល: រៀនសូត្រ)

៣. សម្គាល់ក្នុងការវិភាគល្បះ៖
- ល្បះទោល = [កន្សោមនាម (ប្រធាន)] + [កន្សោមកិរិយា (កិរិយាសព្ទ + កម្មបទ)]`,
    source: 'វេយ្យាករណ៍ភាសាខ្មែរ អនុវិទ្យាល័យ',
    tags: ['វេយ្យាករណ៍', 'កន្សោមនាម', 'កន្សោមកិរិយា', 'មេរៀនសង្ខេប'],
    createdAt: '2024-10-14T16:00:00Z'
  }
];

export const initialYearlyPlan: YearlyPlanItem[] = [
  // Term 1 (ឆមាសទី ១) - October to February
  {
    id: 'yp-1',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'តុលា',
    week: 1,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ១៖ ការស្គាល់ខ្លួនឯង និងសាលារៀន',
    lessonTitle: 'មេរៀនទី ១៖ ការណែនាំខ្លួន និងបទបញ្ជាផ្ទៃក្នុងថ្នាក់រៀន',
    durationHours: 2,
    objectives: 'សិស្សអាចស្គាល់គ្នាក្នុងថ្នាក់ យល់ពីបទបញ្ជាផ្ទៃក្នុង និងរៀបចំកាលវិភាគសិក្សាបានត្រឹមត្រូវ។',
    materials: 'ផ្ទាំងបទបញ្ជាផ្ទៃក្នុង, សៀវភៅតាមដាន, កាតឈ្មោះ',
    assessment: 'សង្កេតការចូលរួម និងការសួរសំណួរផ្ទាល់មាត់',
    status: 'completed',
    notes: 'បានបញ្ចប់ដោយជោគជ័យ សិស្សចូលរួមសកម្ម'
  },
  {
    id: 'yp-2',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'តុលា',
    week: 2,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ១៖ ការស្គាល់ខ្លួនឯង និងសាលារៀន',
    lessonTitle: 'មេរៀនទី ២៖ អត្ថបទអាន «ថ្ងៃដំបូងនៃការចូលរៀន»',
    durationHours: 4,
    objectives: 'សិស្សអាចអានអត្ថបទបានរលូន យល់ន័យពាក្យគន្លឹះ និងឆ្លើយសំណួរស្វែងយល់អត្ថបទបាន។',
    materials: 'សៀវភៅពុម្ព, ប័ណ្ណពាក្យគន្លឹះ, វចនានុក្រមខ្មែរ',
    assessment: 'ការអានឮៗ និងកិច្ចការផ្ទះឆ្លើយសំណួរ',
    status: 'completed',
    notes: ''
  },
  {
    id: 'yp-3',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'តុលា',
    week: 3,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ១៖ ការស្គាល់ខ្លួនឯង និងសាលារៀន',
    lessonTitle: 'មេរៀនទី ៣៖ វេយ្យាករណ៍ «ប្រភេទនៃនាម និងការប្រើប្រាស់»',
    durationHours: 2,
    objectives: 'សិស្សអាចបែងចែករវាងនាមសាធារណ៍ និងនាមអសាធារណ៍ ព្រមទាំងបង្កើតល្បះបាន។',
    materials: 'ក្ដារខៀន, ផ្ទាំងតារាងវេយ្យាករណ៍',
    assessment: 'លំហាត់អនុវត្តក្នុងថ្នាក់',
    status: 'in_progress',
    notes: 'កំពុងបង្រៀនសប្តាហ៍នេះ'
  },
  {
    id: 'yp-4',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'តុលា',
    week: 4,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ១៖ ការស្គាល់ខ្លួនឯង និងសាលារៀន',
    lessonTitle: 'មេរៀនទី ៤៖ សរសេរតាមអាន និងតេស្តប្រចាំខែតុលា',
    durationHours: 2,
    objectives: 'វាយតម្លៃសមត្ថភាពសរសេរអក្ខរាវិរុទ្ធ និងការយល់ដឹងមេរៀនប្រចាំខែដំបូង។',
    materials: 'ក្រដាសតេស្ត, ប៊ិច',
    assessment: 'ពិន្ទុតេស្តប្រចាំខែ',
    status: 'pending',
    notes: ''
  },
  // November
  {
    id: 'yp-5',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'វិច្ឆិកា',
    week: 1,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ២៖ វប្បធម៌ និងប្រពៃណីជាតិ',
    lessonTitle: 'មេរៀនទី ១៖ ព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ',
    durationHours: 4,
    objectives: 'សិស្សស្គាល់ពីប្រភព និងអត្ថន័យនៃពិធីបុណ្យជាតិ ព្រមទាំងចេះសរសេររៀបរាប់ពិធីបុណ្យ។',
    materials: 'រូបភាពពិធីបុណ្យអុំទូក, វីដេអូឯកសារខ្លី',
    assessment: 'តែងសេចក្តីពិពណ៌នាខ្លី',
    status: 'pending',
    notes: ''
  },
  {
    id: 'yp-6',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'វិច្ឆិកា',
    week: 2,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ២៖ វប្បធម៌ និងប្រពៃណីជាតិ',
    lessonTitle: 'មេរៀនទី ២៖ កំណាព្យបទពាក្យ ៧ «មោទនភាពជាតិខ្មែរ»',
    durationHours: 4,
    objectives: 'សិស្សចេះសូត្រកំណាព្យតាមចង្វាក់ពាក្យ៧ និងស្គាល់ចំណាប់ចួនរវាងឃ្លា។',
    materials: 'ផ្ទាំងកំណាព្យ, គំរូសូត្រកំណាព្យ',
    assessment: 'ការសូត្រកំណាព្យផ្ទាល់មាត់',
    status: 'pending',
    notes: ''
  },
  // December
  {
    id: 'yp-7',
    academicYear: '២០២៤-២ solicitation',
    term: 'term1',
    month: 'ធ្នូ',
    week: 1,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ៣៖ បរិស្ថាន និងធម្មជាតិ',
    lessonTitle: 'មេរៀនទី ១៖ ការថែរក្សាព្រៃឈើ និងជីវចម្រុះក្នុងសហគមន៍',
    durationHours: 4,
    objectives: 'សិស្សយល់ពីសារៈសំខាន់នៃបរិស្ថាន និងចេះចូលរួមដាំដើមឈើក្នុងបរិវេណសាលា។',
    materials: 'រូបភាពធម្មជាតិ, ស្លាកអប់រំបរិស្ថាន',
    assessment: 'កិច្ចការជាក្រុម',
    status: 'pending',
    notes: ''
  },
  // January & Exam
  {
    id: 'yp-8',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'មករា',
    week: 3,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ការរំលឹកមេរៀនឡើងវិញ',
    lessonTitle: 'រំលឹកមេរៀនឆមាសទី ១ ត្រៀមប្រឡង',
    durationHours: 6,
    objectives: 'ពង្រឹងចំណេះដឹងគ្រប់ជំពូកដែលបានរៀនក្នុងឆមាសទី១។',
    materials: 'សំណួរចម្លើយត្រៀមប្រឡង',
    assessment: 'លំហាត់សាកល្បង',
    status: 'pending',
    notes: ''
  },
  {
    id: 'yp-9',
    academicYear: '២០២៤-២០២៥',
    term: 'term1',
    month: 'កុម្ភៈ',
    week: 1,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ការវាយតម្លៃឆមាស',
    lessonTitle: 'សម័យប្រឡងឆមាសទី ១',
    durationHours: 4,
    objectives: 'វាស់ស្ទង់ចំណេះដឹងផ្លូវការឆមាសទី១ របស់សិស្សានុសិស្សទូទាំងថ្នាក់។',
    materials: 'វិញ្ញាសាប្រឡងផ្លូវការ',
    assessment: 'ពិន្ទុប្រឡងឆមាសទី១',
    status: 'pending',
    notes: ''
  },
  // Term 2 (ឆមាសទី ២)
  {
    id: 'yp-10',
    academicYear: '២០២៤-២០២៥',
    term: 'term2',
    month: 'មីនា',
    week: 1,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ៤៖ អក្សរសិល្ប៍ និងរឿងព្រេងខ្មែរ',
    lessonTitle: 'មេរៀនទី ១៖ សិក្សារឿងព្រេង «ក្រពើអាធន»',
    durationHours: 4,
    objectives: 'សិស្សអាចវិភាគតួអង្គ រកគំនិតអប់រំ និងសរសេរសេចក្តីសង្ខេបរឿងបាន។',
    materials: 'សៀវភៅរឿងព្រេងខ្មែរ, រូបគំនូរតួអង្គ',
    assessment: 'ការឆ្លើយសំណួរវិភាគតួអង្គ',
    status: 'pending',
    notes: ''
  },
  {
    id: 'yp-11',
    academicYear: '២០២៤-២០២៥',
    term: 'term2',
    month: 'ឧសភា',
    week: 2,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ជំពូកទី ៥៖ វិទ្យាសាស្ត្រ និងបច្ចេកវិទ្យា',
    lessonTitle: 'មេរៀនទី ១៖ តួនាទីនៃអ៊ីនធឺណិតក្នុងការសិក្សាស្រាវជ្រាវ',
    durationHours: 4,
    objectives: 'សិស្សចេះប្រើប្រាស់អ៊ីនធឺណិតប្រកបដោយសុវត្ថិភាព និងជាប្រយោជន៍ដល់ការសិក្សា។',
    materials: 'កុំព្យូទ័រ, បទបង្ហាញស្លាយ',
    assessment: 'កិច្ចការស្រាវជ្រាវខ្នាតតូច',
    status: 'pending',
    notes: ''
  },
  {
    id: 'yp-12',
    academicYear: '២០២៤-២០២៥',
    term: 'term2',
    month: 'កក្កដា',
    week: 2,
    subject: 'ភាសាខ្មែរ',
    grade: '៧',
    chapter: 'ការបញ្ចប់ឆ្នាំសិក្សា',
    lessonTitle: 'ប្រឡងបញ្ចប់ឆមាសទី ២ និងបូកសរុបលទ្ធផលប្រចាំឆ្នាំ',
    durationHours: 6,
    objectives: 'វាយតម្លៃលទ្ធផលចុងក្រោយប្រចាំឆ្នាំ និងចេញចំណាត់ថ្នាក់សិស្ស។',
    materials: 'វិញ្ញាសាប្រឡង, តារាងស្រង់ពិន្ទុ',
    assessment: 'ពិន្ទុប្រឡងឆមាសទី២ & មធ្យមភាគប្រចាំឆ្នាំ',
    status: 'pending',
    notes: ''
  }
];
